### ISSUE TITLE
仙子可以增加一张截图吗？

### ISSUE THREAD

**Issue by dpluy** [lilydjwg/myawesomerc#2]
期待有图

**Comment by lilydjwg** [comment]
并没有什么特别的地方啊：

![QQ截图](https://lilyimg.b0.upaiyun.com/blog/wine-qqlite-7.5/wine-qqlite7.5.png)
![](https://lilyimg.b0.upaiyun.com/blog/awesome-github-widget/awesome-desktop.png)

**Comment by dpluy** [comment]
有截图，才了解这份配置的强大啊

**Comment by lilydjwg** [comment]
那个得录视频的说，还要带键盘按键显示的。

**Comment by dpluy** [comment]
那估计会是新手的福音啦，haha
