### ISSUE TITLE
archlinux awesomewm 下 tim 的问题

### ISSUE THREAD

**Issue by Graywd** [lilydjwg/myawesomerc#3]
hi，你好， 

我只在 arch 上面 装了 awesomewm ，接着装了 deepin-tim
tim 看起来能运行， 但界面的渲染很慢， 而且点击的时候总点不到， 
找了找， 就通过 arch 上面的 wiki 找到这来了。

是我还少配置了某个地方吗？ 补充一句， 我没有桌面环境这些。

**Comment by lilydjwg** [comment]
我这里也挺慢的，点击的时候点不动的话，尝试移动窗口，有可能会移动出一个完全不响应事件的窗口，底下有个真正能用的窗口。

PS: 我用的是 [QQLite](https://blog.lilydjwg.me/2015/10/26/run-tencent-qq-lite-with-wine.186640.html)。

**Comment by Graywd** [comment]
wine 不熟悉，暂时直接用的虚拟机跑的， 唯一的好处可能就是稳定了 ^-^
